# Generated by Django 4.2.7 on 2023-11-04 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_number",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(999999999999),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
