# Generated by Django 4.2.7 on 2023-11-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0002_alter_user_deleted_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount", old_name="user_id", new_name="user",
        ),
    ]
