# Generated by Django 4.2.7 on 2023-11-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0003_rename_user_id_useraccount_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
